version: '3.6'

services:
  rmt-new-frontend:
    image: $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:dev
    container_name: $APP-dev
    env_file: $ENV_DEV
    ports:
      - 9002:8080
    restart: always
